add-looking-for: Add more information about things we want in the test
Gympass/interview-test pull request #1
Opened 2019-03-01 19:14 UTC by gadsc

2019-03-01 19:17 UTC, vsabreu commented on README.md
> +* Separação de clara de responsabilidades (Domínios, Serviços, Repositórios, etc);
typo here: `Separação clara de responsabilidades`.

2019-03-01 19:18 UTC, vsabreu commented on README.md
> +* Tratamento de Erro;
`Tratamento de erros`

2019-03-01 19:18 UTC, vsabreu requested changes
small typos

2019-03-01 19:24 UTC, paulinobruno commented on README.md
> +GOSTARÍAMOS DE VER
Guys, do you think we should state clearer what we want (must have) from what we'd like to see (nice to have)?
I really think *Tests* are not a Nice to Have.

2019-03-01 19:30 UTC, renandsiqueira commented on README.md
> +* Testes;
```suggestion
* Testes necessários para manter a qualidade do seu código;
```

2019-03-01 20:46 UTC, renandsiqueira commented on README.md
> +* Testes;
```suggestion
* Garanta a qualidade do seu código;
```

2019-07-29 19:25 UTC, otavioucdb approved these changes

2019-07-29 19:26 UTC, merged